apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zkrwq21h3-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/zkrwq21h3-java-quarkus